@echo off
cd /d %~dp0
echo [1/4] resuming 3B download (auto-resumes partial files)...
python -c "import env_setup; from huggingface_hub import snapshot_download; snapshot_download('Qwen/Qwen2.5-3B-Instruct')"
echo [2/4] extracting vectors on 3B...
python scripts/step1_extract.py
echo [3/4] generating (live output, incremental save, resumable)...
python scripts/step2_generate.py
echo [4/4] scoring and report...
python scripts/step3_report.py
pause
